### ISSUE TITLE
nsh fails to compile

### ISSUE THREAD

**Issue by GoldsteinE** [nuta/nsh#7]
rustc 1.48.0 (7eac88abb 2020-11-16)
Linux lptp 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

I get this error while compiling nsh:
```
error[E0277]: `&SignalsInfo` is not an iterator
   --> src/mainloop.rs:137:27
    |
137 |             for signal in &signals {
    |                           ^^^^^^^^ `&SignalsInfo` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `&SignalsInfo`
    = note: required by `into_iter`
```

**Comment by nuta** [comment]
I've pushed a fix for your problem. Could you try `master` branch?

**Comment by nuta** [comment]
v0.4.0 should fix this bug. Please reopen if it still reproduces.
